/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'applicants': RouteRecordInfo<'applicants', '/applicants', Record<never, never>, Record<never, never>>,
    'application-stats': RouteRecordInfo<'application-stats', '/application-stats', Record<never, never>, Record<never, never>>,
    'applied-jobs': RouteRecordInfo<'applied-jobs', '/applied-jobs', Record<never, never>, Record<never, never>>,
    'authorization-status': RouteRecordInfo<'authorization-status', '/authorization-status', Record<never, never>, Record<never, never>>,
    'brand-kit': RouteRecordInfo<'brand-kit', '/brand-kit', Record<never, never>, Record<never, never>>,
    'browse-gigs': RouteRecordInfo<'browse-gigs', '/browse-gigs', Record<never, never>, Record<never, never>>,
    'browse-jobs': RouteRecordInfo<'browse-jobs', '/browse-jobs', Record<never, never>, Record<never, never>>,
    'browse-templates': RouteRecordInfo<'browse-templates', '/browse-templates', Record<never, never>, Record<never, never>>,
    'calendar': RouteRecordInfo<'calendar', '/calendar', Record<never, never>, Record<never, never>>,
    'caption-generator': RouteRecordInfo<'caption-generator', '/caption-generator', Record<never, never>, Record<never, never>>,
    'create-post': RouteRecordInfo<'create-post', '/create-post', Record<never, never>, Record<never, never>>,
    'current-plan': RouteRecordInfo<'current-plan', '/current-plan', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'discover-talent': RouteRecordInfo<'discover-talent', '/discover-talent', Record<never, never>, Record<never, never>>,
    'image-enhancer': RouteRecordInfo<'image-enhancer', '/image-enhancer', Record<never, never>, Record<never, never>>,
    'interview-scheduler': RouteRecordInfo<'interview-scheduler', '/interview-scheduler', Record<never, never>, Record<never, never>>,
    'invoice-history': RouteRecordInfo<'invoice-history', '/invoice-history', Record<never, never>, Record<never, never>>,
    'invoices-history': RouteRecordInfo<'invoices-history', '/invoices-history', Record<never, never>, Record<never, never>>,
    'job-insights': RouteRecordInfo<'job-insights', '/job-insights', Record<never, never>, Record<never, never>>,
    'job-listings': RouteRecordInfo<'job-listings', '/job-listings', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'manage-accounts': RouteRecordInfo<'manage-accounts', '/manage-accounts', Record<never, never>, Record<never, never>>,
    'messages': RouteRecordInfo<'messages', '/messages', Record<never, never>, Record<never, never>>,
    'my-gigs': RouteRecordInfo<'my-gigs', '/my-gigs', Record<never, never>, Record<never, never>>,
    'my-profile': RouteRecordInfo<'my-profile', '/my-profile', Record<never, never>, Record<never, never>>,
    'my-proposals': RouteRecordInfo<'my-proposals', '/my-proposals', Record<never, never>, Record<never, never>>,
    'my-templates': RouteRecordInfo<'my-templates', '/my-templates', Record<never, never>, Record<never, never>>,
    'notification-settings': RouteRecordInfo<'notification-settings', '/notification-settings', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'password-login-info': RouteRecordInfo<'password-login-info', '/password-login-info', Record<never, never>, Record<never, never>>,
    'performance-overview': RouteRecordInfo<'performance-overview', '/performance-overview', Record<never, never>, Record<never, never>>,
    'platform-reports': RouteRecordInfo<'platform-reports', '/platform-reports', Record<never, never>, Record<never, never>>,
    'portfolio': RouteRecordInfo<'portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    'post-ideas': RouteRecordInfo<'post-ideas', '/post-ideas', Record<never, never>, Record<never, never>>,
    'post-job': RouteRecordInfo<'post-job', '/post-job', Record<never, never>, Record<never, never>>,
    'posts-library': RouteRecordInfo<'posts-library', '/posts-library', Record<never, never>, Record<never, never>>,
    'profile-settings': RouteRecordInfo<'profile-settings', '/profile-settings', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'resume-builder': RouteRecordInfo<'resume-builder', '/resume-builder', Record<never, never>, Record<never, never>>,
    'saved-jobs': RouteRecordInfo<'saved-jobs', '/saved-jobs', Record<never, never>, Record<never, never>>,
    'saved-profiles': RouteRecordInfo<'saved-profiles', '/saved-profiles', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'security-login': RouteRecordInfo<'security-login', '/security-login', Record<never, never>, Record<never, never>>,
    'top-posts': RouteRecordInfo<'top-posts', '/top-posts', Record<never, never>, Record<never, never>>,
    'upgrade-downgrade': RouteRecordInfo<'upgrade-downgrade', '/upgrade-downgrade', Record<never, never>, Record<never, never>>,
    'upgrade-plan': RouteRecordInfo<'upgrade-plan', '/upgrade-plan', Record<never, never>, Record<never, never>>,
  }
}
